### ISSUE TITLE
Multiple occurrences

### ISSUE THREAD

**Issue by pinta83** [EmranAhmed/chosen-icon#1]
I have a page with two chosenIcon elements, and only the last one has icons in it....
I've set up the second element to exec chosenIcon in a timeout of 5 seconds... As soon as the second element gets converted to chosenIcon - the first one neve shows icons again.....

**Comment by EmranAhmed** [comment]
@pinta83 I am not continuing this development. You can use this [Selectize](http://brianreavis.github.io/selectize.js/)
